### ISSUE TITLE
Update to systemd 246

### ISSUE THREAD

**Issue by tjkirch** [bottlerocket-os/bottlerocket#1015]
https://github.com/systemd/systemd/blob/master/NEWS

I tried updating from systemd 245 to 246, but the wicked nanny service fails to start about half of the time, maybe more - maybe a timing issue.  So far all I have is the console message saying "Failed to start wicked network nanny service", which prevents most networking from starting up.

**Comment by bcressey** [comment]
We're hitting SELinux denials because of two changes in v246.


https://github.com/systemd/systemd/commit/4f07ddfa9bc2242eaa6c288a15b8bce4e4383931 causes this kernel denial:
```
avc:  denied  { write } for
  pid=1 comm="systemd"
  path="pipe:[12129]" dev="pipefs" ino=12129
  scontext=system_u:system_r:init_t:s0
  tcontext=system_u:system_r:api_t:s0
  tclass=fifo_file permissive=0
```

https://github.com/systemd/systemd/commit/77ee1783ebc8385013e95161427e1f945691ced0 causes this userspace denial:
```
Sep 18 21:35:11 localhost systemd[1]: Starting D-Bus System Message Bus...
Sep 18 21:35:11 localhost systemd[286]: selinux: avc:  netlink recvfrom: error 9
```

(PID 286 is dbus-broker-launcher.)

**Comment by bcressey** [comment]
The userspace denial seems harmless. The `EBADFD` or bad file descriptor error happens only when starting dbus-broker, 
apparently because systemd is trying to access the dbus socket before the server is ready.
