### ISSUE TITLE
Enabling bpf-lsm security module and both CAP_BPF and CAP_PERFMON security capabilities

### ISSUE THREAD

**Issue by danmx** [bottlerocket-os/bottlerocket#1063]
**What I'd like:**

I'd like to see `bpf-lsm` (BPF-based Linux Security Module, introduced in kernel 5.7) and both `CAP_BPF` and CAP_PERFMON security capabilities (introduced in kernel 5.8) enabled.

**Any alternatives you've considered:**

**Comment by webern** [comment]
Good ideas, thank you for bringing these to our attention. It may be some time before we move to these kernel versions, but we'll take a closer look at this.

**Comment by danmx** [comment]
We could port those patches to the current kernel. I don’t have much experience with it but with some guidance I could try contributing.

**Comment by WilboMo** [comment]
Hello danmx. Since our last correspondence on this issue, the features you’re looking for have been added in newer [variants](https://github.com/bottlerocket-os/bottlerocket/tree/develop/variants#bottlerocket-variants) of Bottlerocket like aws-k8s-1.20 and aws-k8s-1.21 through use of the 5.10 kernel. You can find AMIs for these variants through the web console [here](https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami-bottlerocket.html) or via command line as shown [here](https://github.com/bottlerocket-os/bottlerocket/blob/develop/QUICKSTART-EKS.md#finding-an-ami). Instructions on launching Bottlerocket nodes can be found [here](https://github.com/bottlerocket-os/bottlerocket/blob/develop/QUICKSTART-EKS.md#using-a-bottlerocket-ami-with-amazon-eks). Please let us know if you have any other issues or concerns.

**Comment by kdaula** [comment]
Resolving, since bpf-lsm and the new capabilities are available in newer variants.
