### ISSUE TITLE
[ECS] GPU support

### ISSUE THREAD

**Issue by samuelkarp** [bottlerocket-os/bottlerocket#1074]
This issue is tracking adding support for GPU devices to the ECS variant of Bottlerocket.

This will require adding the Nvidia kernel module and userspace drivers.

**Comment by kniec** [comment]
Hey, super interested in that issue as it related to a lot what the HPC community would want BottleRocket to use for. As I wrote in the (renamed) EKS issue #769: I would like the container to provide the userland driver and not do a bind-mount for that. 
From my HPC PoV the extreme benefit of bottlerocket in this scenario would be that a customer can identify a reproducible OS host system (hash or tag) and together with the container sha256 provide a reproducible execution environment that does not leave room for interpretation. While the tuple would allow the host to add a driver to the container, I would like to keep that seperate.

**Comment by arnaldo2792** [comment]
Hey @kniec, for our kubernetes GPU support we went ahead with the general approach of mounting the userland driver in containers, since as described in the issue you linked, we didn't want customers to rethink how they have to build their container images. However, I do think that your use case could be supported in Bottlerocket, but we need to design how we actually want to do it. I'll bring your use case up to the team and discuss if we will support it in future releases.
