### ISSUE TITLE
Container runtime: Kubelet says its running dockershim.sock but the runtime is containerd on `kubelet get nodes`

### ISSUE THREAD

**Issue by abhijitherekar** [bottlerocket-os/bottlerocket#1126]
**Image I'm using:**
```
 k get node -o wide
NAME                                           STATUS   ROLES    AGE   VERSION   INTERNAL-IP      EXTERNAL-IP      OS-IMAGE                KERNEL-VERSION   CONTAINER-RUNTIME
ip-192-168-48-245.us-west-2.compute.internal   Ready    <none>   17h   v1.17.9   192.168.48.245   34.216.135.185   Bottlerocket OS 1.0.1   5.4.50           containerd://1.3.7+unknown
```
Then when I check for kubelet I see this:
```
bash-4.2# cat /proc/4092/cmdline 
/usr/bin/kubelet--cloud-provideraws--config/etc/kubernetes/kubelet/config--kubeconfig/etc/kubernetes/kubelet/kubeconfig--container-runtime=remote--container-runtime-endpoint=unix:///run/dockershim.sock--containerd=/run/dockershim.sock--network-plugincni--root-dir/var/lib/kubelet--cert-dir/var/lib/kubelet/pki--volume-plugin-dir/var/lib/kubelet/plugins/volume/exec--node-ip192.168.48.245--node-labelsalpha.eksctl.io/cluster-name=my-cluster,alpha.eksctl.io/nodegroup-name=ng-bottlerocket--register-with-taints--pod-infra-container-image602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/pause-amd64:3.1
bash-4.2# 
bash-4.2# 
```

**What I expected to happen:**
I should see that the docker runtime should be present as the kubelet says its using the docker but the nodes says they are running containerd. 

**What actually happened:**
Containerd was running instead of the docker-runtime. 

**How to reproduce the problem:**
Create a BottleRocket EKS and we should see this. 

Also, I see this default values here: https://github.com/bottlerocket-os/bottlerocket/blob/develop/sources/models/defaults.toml#L24

Is the above default file is over-riding the runtime? If thats the case then it should be fixed to show in kubelet the correct container-runtime. 

Is there a config which overrides the kubelet? 
If there is one then please, let me know and we can close the issue.

**Comment by samuelkarp** [comment]
Hi @abhijitherekar! The Kubelet is showing the correct output; we use containerd as the container runtime for our Kubernetes variants instead of Docker.  However, we do [override containerd's socket to be `dockershim.sock`](https://github.com/bottlerocket-os/bottlerocket/blob/0ee62e6b37bc9a1768943afdf280295f05af77ce/packages/containerd/containerd-config-toml_aws-k8s#L12-L13) because [the default aws-k8s-cni config expects that](https://github.com/bottlerocket-os/bottlerocket/issues/747).  We're using https://github.com/bottlerocket-os/bottlerocket/issues/801 to track further changes here.
