### ISSUE TITLE
[ECS] Instance store volumes support

### ISSUE THREAD

**Issue by improved-broccoli** [bottlerocket-os/bottlerocket#1145]
**What I'd like:**

After opening a ticket on AWS Support to find out how to mount an instance store volume on a container instance running Bottlerocket in an ECS cluster, the agent told me this was not supported for now, but something will be released for EKS in a near future and that I should create a ticket for the same feature on ECS to track the progress.

So my feature request is simple: provide the ability to mount an instance store volume like described in [EC2 docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/add-instance-store-volumes.html#making-instance-stores-available-on-your-instances).
Ideally this feature should allow to specify:
* filesystem format
* mount point
* device to mount

**Any alternatives you've considered:**
None

**Comment by jahkeup** [comment]
Hi @jbenoit2011, thanks for creating this issue! Instance storage is definitely on our radar - we'll use this issue to hold discussion and for any ECS-specifics that may come up.

I'm adding the appropriate label to keep track as we dig into ECS feature work & related storage issues (such as #1088).

**Comment by bcressey** [comment]
We're tracking this in #1209.

It won't quite be what you've asked for since "device to mount" is inherently somewhat ambiguous, and may be different across reboots or on different platforms.

It also doesn't offer flexibility on specifying the mount point for a similar reason - if devices can't be identified with precision, it's hard to be sure what will end up on the mount point.

Feedback on the proposed design is welcome.
