### ISSUE TITLE
`cargo make ami` fails on macOS around `BUILDSYS_ARCH`.

### ISSUE THREAD

**Issue by izaakschroeder** [bottlerocket-os/bottlerocket#1162]
`cargo make ami` doesn't work properly on macOS.

**Platform I'm building on:**

macOS

**What I expected to happen:**

`cargo make ami` to build without errors.

**What actually happened:**

```
/var/folders/_8/37v4m93x6xg162jyl200y5nw0000gn/T/izaakschroeder/fsio/v0FfHrk3Iz.sh: line 26: ${BUILDSYS_ARCH,,}: bad substitution
```

**How to reproduce the problem:**

Run `cargo make ami` on macOS.

**Comment by tjkirch** [comment]
Hi @izaakschroeder - I'm afraid you caught us in an awkward time, since we just replaced the amiize.sh script and were about to remove it from the repo.  Would you be up for trying the replacement?  It's documented in our [PUBLISHING](https://github.com/bottlerocket-os/bottlerocket/blob/develop/PUBLISHING.md) guide.

**Comment by izaakschroeder** [comment]
Oh 😢 no worries! Sorry about that, I didn't realize. I can give it a whirl and see if it suffers from the same problem though!

**Comment by izaakschroeder** [comment]
This is where I'm at right now:

```sh
[cargo-make] INFO - Running Task: link-variant
[cargo-make] INFO - Build Done in 2577 seconds.
❯ cargo make ami -e PUBLISH_REGIONS="us-west-2" -e PUBLISH_AMI_NAME="bottlerocket-aws-k8s-1.17-x86_64-bpffs-test"
[cargo-make] INFO - cargo make 0.32.5
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: ami
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: setup
[cargo-make] INFO - Running Task: fetch-sources
[cargo-make] INFO - Running Task: publish-tools
[cargo-make] INFO - Running Task: ami
/Users/izaakschroede : decoded 2147483648 bytes
/Users/izaakschroede : decoded 1073741824 bytes
/var/folders/_8/37v4m93x6xg162jyl200y5nw0000gn/T/izaakschroeder/fsio/v0FfHrk3Iz.sh: line 26: ${BUILDSYS_ARCH,,}: bad substitution
```

I'll continue to investigate!

**Comment by izaakschroeder** [comment]
Alright so patching

```sh
# Canonicalize architecture identifier to the value recognized by EC2.
case "${BUILDSYS_ARCH,,}" in
```

to

```sh
# Canonicalize architecture identifier to the value recognized by EC2.
case "${BUILDSYS_ARCH}" in
```

and adding a root `Infra.toml` with

```toml
[repo.default]
root_role_url = "https://cache.bottlerocket.aws/root.json"
root_role_sha512 = "90393204232a1ad6b0a45528b1f7df1a3e37493b1e05b1c149f081849a292c8dafb4ea5f7ee17bcc664e35f66e37e4cfa4aae9de7a2a28aa31ae6ac3d9bea4d5"
```

is enough; it results in:

```
05:53:07 [INFO] Registering 'bottlerocket-aws-k8s-1.17-x86_64-bpffs-test' in us-west-2
05:53:42 [INFO] Waiting for root and data snapshots to become available in us-west-2
05:53:53 [INFO] Making register image call in us-west-2
05:53:53 [INFO] Registered AMI 'bottlerocket-aws-k8s-1.17-x86_64-bpffs-test' in us-west-2: ami-059480db26b1c0728
```

It feels like it would be nice if there was a way to avoid needing to make the `Infra.toml`… but at least it's working for the most part now! The one patch above might be handy for `macOS` folks though. 😄  I've updated this issue to reflect that!

I'll close https://github.com/bottlerocket-os/bottlerocket/pull/1161 (though https://github.com/bottlerocket-os/bottlerocket/pull/1160 shouldn't be effected by this).

**Comment by zmrow** [comment]
Thanks for the issue!

In regards to the parameter expansion `"${BUILDSYS_ARCH,,}"`: this should work in any version of bash since version 4.  I'm fairly certain that MacOS (unfortunately) ships an old version of bash by default. You can check with `bash --version`.  Is that the case?  If not, let us know.  

In regards to the `cargo make ami` issues - do you mind pasting in your entire `Infra.toml` (omitting any secrets of course!)  I don't think you should need to have a `[repo]` section to build AMIs.  I agree that not having to create an `Infra.toml` would be nice, but in the case of building AMIs we need to know where to build them, credential roles to use (if applicable), etc.

**Comment by tjkirch** [comment]
> in the case of building AMIs we need to know where to build them

You should be able to build an AMI with just `cargo make ami -e PUBLISH_REGIONS=my-region-1`, as you had, without an Infra.toml.  It seems we introduced a bug somewhere.  (The file can actually be empty, you don't need the repo section, which makes it even clearer that it's a bug.)  I'll take a look.

Regarding bash, that's... unfortunate.  I'd rather move toward compatible code in Rust than add hacks for older tools, though.  For now, I suppose we'd need to replace the `,,` with another way to lowercase the BUILDSYS_ARCH, or just say that we don't support uppercase (since that's weird to specify in the first place).

**Comment by zmrow** [comment]
I believe we've fixed the problems in this issue! Please feel free to re-open if there's something we overlooked.
