### ISSUE TITLE
Add support for HTTP_PROXY environment variable configuration into various services

### ISSUE THREAD

**Issue by yeolahm** [bottlerocket-os/bottlerocket#1178]
**What I'd like:**
I would like to add  HTTP_PROXY related environment variables to the various services (example - kubelet & containerd/docker) configuration files so that they can connect to the internet through the proxy server.

May be global configuration that allows HTTP_PROXY environment variables and parameter in each service to enable global config.

**Any alternatives you've considered:**
No, as I understand, by design it is not possible to dynamically add any configuration that does not exist into the [data models](https://github.com/bottlerocket-os/bottlerocket/tree/develop/sources/models)

**Comment by bcressey** [comment]
Notes to check my understanding:

Goal is only to enable proxy usage for host level components (containerd, kubelet, host-ctr). We do not need to worry about injecting the variables into pod enviroments.

kubelet may or may not need a proxy in an EC2 VPC if connecting to the private IP of the API server. May need to special case this somehow, e.g. a default value for NO_PROXY that includes the API server hostname. Fallback would be separate proxy settings for kubelet, containerd in addition to global settings.

Web proxy URIs may contain user credentials. Since they will be rendered via template into configuration files under `/etc`, or dynamically set in the environment where they can be obtained from `/proc/<pid>/environ`, there's no immediate expectation that these settings will be stored in an encrypted form in the datastore.
