### ISSUE TITLE
Building an image with Buildkit is blocked by SELinux

### ISSUE THREAD

**Issue by ryansch** [bottlerocket-os/bottlerocket#1187]
**Image I'm using:**
Image referenced in SSM:
```
/aws/service/bottlerocket/aws-ecs-1/x86_64/1.0.2/image_id
```

**What I expected to happen:**
I expected to be able to use `export DOCKER_BUILDKIT=1`, and `export COMPOSE_DOCKER_CLI_BUILD=1` to build with buildkit.

**What actually happened:**
I started with a simple Dockerfile:
```Dockerfile
FROM alpine:latest
RUN touch /foo
```

When trying to build the image on a bottlerocket instance, I received:
```
#5 0.492 touch: /foo: Permission denied
```

And I found the following error via `logdog`:
```
[ 1876.028655] audit: type=1400 audit(1603904993.869:4): avc:  denied  { write } for  pid=4910 comm="touch" name="/" dev="overlay" ino=795374 scontext=system_u:system_r:container_t:s0 tcontext=system_u:object_r:cache_t:s0 tclass=dir permissive=0
```

I'm able to build that image on the same instance if I unset `DOCKER_BUILDKIT` and `COMPOSE_DOCKER_CLI_BUILD`.

I tried elevating privileges for the container calling `docker-compose build` but that doesn't appear to have any effect on the actual build containers.

**Comment by samuelkarp** [comment]
Hi! I was able to reproduce the behavior you described; it looks like we might need to adjust the labels on the directory that buildkit is using for building images (from initial looking, everything under `/var/lib/docker/buildkit` has `local_t`, but might need `cache_t` instead).

I'll mark this as a bug, because it's surprising behavior, but I'd really appreciate more information on the use-case that you have here.  We've seen a few other requests to use Bottlerocket as an image build host, but that hasn't been the focus of our design so far (and image build has some different characteristics as compared to running images that we'd need to account for in terms of security and hardening).  It's also somewhat of an implementation detail that the `aws-ecs-1` variant uses Docker today; our Kubernetes variants use containerd instead.  Can you tell me more about your workflow?

**Comment by ryansch** [comment]
@samuelkarp We're currently using bottlerocket in an ECS cluster to run buildkite agents for our CI setup. As such, we need to be able to build images before running tests on them.

**Comment by bcressey** [comment]
Docker 19.03.15 and 20.10.3 have this release note:
> Ensure AppArmor and SELinux profiles are applied when building with BuildKit

I expect what's needed here is now just an update to the latest version.

**Comment by samuelkarp** [comment]
> I expect what's needed here is now just an update to the latest version.

@bcressey I'm still able to reproduce this bug with a build of Bottlerocket from the latest sources (which includes Docker 19.03.15).

**Comment by bcressey** [comment]
With this Dockerfile, it's more clear what the problem is:
```
FROM amazonlinux:2
RUN cat /proc/self/mountinfo && touch /foo
```

The container is running with its expected process label and some of the mounts have the "context=" option that's needed, but `/` does not.

```
#5 0.231 518 363 0:71 / / rw,relatime master:147 - overlay overlay rw,seclabel,lowerdir=/var/lib/docker/overlay2/l/TS7YMF3DEUPUPMBQFOTAMIBRVJ,upperdir=/var/lib/docker/overlay2/owsz49krelfle1kgdwjwtv8d3/diff,workdir=/var/lib/docker/overlay2/owsz49krelfle1kgdwjwtv8d3/work
#5 0.231 519 518 0:74 / /proc rw,nosuid,nodev,noexec,relatime - proc proc rw
#5 0.231 520 518 0:75 / /dev rw,nosuid - tmpfs tmpfs rw,context="system_u:object_r:data_t:s0:c418,c773",size=65536k,mode=755
```

**Comment by ryansch** [comment]
I just hit this again when I rolled out an image using docker compose v2. This may force us to move away from bottlerocket unless we can figure out a workaround.

**Comment by ryansch** [comment]
I'm able to build images on bottlerocket 1.5.2 with compose v2.
