### ISSUE TITLE
Support For Custom Certificates

### ISSUE THREAD

**Issue by woodwoc** [bottlerocket-os/bottlerocket#1277]
As a bottlerocket customer I would like the ability to install custom certificates within BottleRocket in order to access a private docker repository and pull down container images.  One potential solutions might include injecting the certificate as part of Userdata like what can be done with Amazon Linux optimized EKS images.

**Comment by arnaldo2792** [comment]
We have been brainstorming different ways to implement this feature, and we have a design candidate that we wanted to share.

The proposed API shape will be as follows:

```toml
# In user data
[settings.pki.my-cert-bundle]
data="---BEGIN CERTIFICATE--..."
trusted=true
[settings.pki.another-cert-bundle]
data="---BEGIN CERTIFICATE--..."
trusted=true
[settings.pki.a-bad-cert]
data="---BEGIN CERTIFICATE--..."
trusted=false
```

```sh
# Using the apiclient
apiclient set \
   pki.my-cert-bundle.data="---BEGIN.." \
   pki.my-cert-bundle.trusted=true \
   pki.another-cert-bundle.data="---BEGIN.." \
   pki.another-cert-bundle.trusted=true \
   pki.a-bad-cert.data="---BEGIN.." \
   pki.a-bad-cert.trusted=false
```

In this solution, users can name the single cert/certificates bundle that the data field represents, which helps them keep the store organized. With this API shape, users can add more bundles in subsequent calls to the API, without them having to re-create the entire store. This allows users to add individual certificates to the existing store by just adding a new record.

The downside of this API shape is that a user can’t effectively remove the record (not to be confused with the certificate bundle in the record) from the API store. This is a problem when a user wants to trust certificates ahead of time, prior for them to be included in the next CA bundle. Once the certificates are part of the CA bundle, the user would like to “delete” the certificates from the API rather than marking them as distrusted. To work around this problem and “remove but trust” certificates in the final bundle the user has two options:

* If the record has a single certificate, set data as an empty string and mark the record as distrusted
* If the record is a bundle, update the record’s data with the updated bundle

We considered using an enabled flag to ignore certificate records, but we decided against this since we want to actually [add support to delete settings from the API](https://github.com/bottlerocket-os/bottlerocket/issues/1584). Once we implement deleting settings from the API, users would be able to effectively delete the certificate records without any work around.

**Comment by arnaldo2792** [comment]
An alternative we considered was for the API to accept separate lists to trust and distrust certificates bundles, as follows:

```toml
# In user data
[settings.pki.]
trusted-certificates=["---BEGIN...", "---BEGIN..."]
distrusted-certificates=["---BEGIN...", "---BEGIN..."]
```

```sh
# Using the apiclient
apiclient set \
   pki.trusted-certificates=["---BEGIN...", "---BEGIN..."] \
   pki.distrusted-certificates=["---BEGIN...", "---BEGIN..."]
```

Both `trusted-certificates` and `distrusted-certificates` would accept a string with N certificates, so the user will be responsible of creating the bundle and properly passing it to the user data. By using this shape, the users could effectively remove undesired certificate blobs by just omitting them from the lists. However, because the list might end up empty, this would still require support for empty settings as in solution 1.

Another downside of this implementation is that in subsequent calls with `apiclient` the users have to pass the certificates they already stored along with the new bundles, since the lists will be replaced with the new values. This only is a problem when users don’t have easy access to their certificates source, and have to recreate the entire bundle from scratch.

We decided against this approach since we liked the user experience in the first solution better, both for updating the certificate store and for keeping it organized.
