### ISSUE TITLE
Running "cargo make --env-file <file>" doesn't work?

### ISSUE THREAD

**Issue by diranged** [bottlerocket-os/bottlerocket#1310]
**Platform I'm building on:**
We're using AWS CodeBuild to try to build our own customized versions of the BottleRocket OS image (see #1307). To try to provide consistent build flags, we created a `cargo.env` file and added in `BUILDSYS_VARIANT=...`, `BUILDSYS_ARCH=...`, `PUBLISH_DATA_VOLUME_SIZE=...` and `GRANT_TO_USERS=...`:

```
# Prepare a cargo.env file with all of our build settings
- echo "BUILDSYS_NAME=${BUILDSYS_NAME}" >> cargo.env
- echo "BUILDSYS_VARIANT=${BUILDSYS_VARIANT}" >> cargo.env
- echo "BUILDSYS_ARCH=${BUILDSYS_ARCH}" >> cargo.env
- echo "GRANT_TO_USERS=${GRANT_TO_USERS}" >> cargo.env
- echo "PUBLISH_DATA_VOLUME_SIZE=${PUBLISH_DATA_VOLUME_SIZE}" >> cargo.env
```

Then our cargo commands were all written like this (following the [cargo-make example](https://github.com/sagiegurari/cargo-make#env-file))
```
- cargo make --env-file cargo.env
- cargo make ami --env-file cargo.env
- cargo make grant-ami --env-file cargo.env
```

**What I expected to happen:**
We expected that the variables set in the `cargo.env` file were going to be honored by the build process. 

**What actually happened:**
The build process kicked off - but as if we had not set those files at all. The variant, arch, root volume size, etc were all pulled from the stock details.

```

2021-02-08T22:15:56.690-08:00 | [Container] 2021/02/09 06:15:55 Running command echo "BUILDSYS_NAME=${BUILDSYS_NAME}" >> cargo.env
-- | --
  | 2021-02-08T22:15:56.690-08:00 |  
  | 2021-02-08T22:15:56.690-08:00 | [Container] 2021/02/09 06:15:55 Running command echo "BUILDSYS_VARIANT=${BUILDSYS_VARIANT}" >> cargo.env
  | 2021-02-08T22:15:56.690-08:00 |  
  | 2021-02-08T22:15:56.690-08:00 | [Container] 2021/02/09 06:15:55 Running command echo "BUILDSYS_ARCH=${BUILDSYS_ARCH}" >> cargo.env
  | 2021-02-08T22:15:56.690-08:00 |  
  | 2021-02-08T22:15:56.690-08:00 | [Container] 2021/02/09 06:15:55 Running command echo "GRANT_TO_USERS=${GRANT_TO_USERS}" >> cargo.env
  | 2021-02-08T22:15:56.690-08:00 |  
  | 2021-02-08T22:15:56.690-08:00 | [Container] 2021/02/09 06:15:55 Running command echo "PUBLISH_DATA_VOLUME_SIZE=${PUBLISH_DATA_VOLUME_SIZE}" >> cargo.env
  | 2021-02-08T22:15:56.690-08:00 |  
  | 2021-02-08T22:15:56.690-08:00 | [Container] 2021/02/09 06:15:55 Running command cat cargo.env
  | 2021-02-08T22:15:56.690-08:00 | BUILDSYS_NAME=nd-bottlerocket
  | 2021-02-08T22:15:56.690-08:00 | BUILDSYS_VARIANT=aws-k8s-1.18
  | 2021-02-08T22:15:56.690-08:00 | BUILDSYS_ARCH=x86_64
  | 2021-02-08T22:15:56.690-08:00 | GRANT_TO_USERS=xxx
  | 2021-02-08T22:15:56.690-08:00 | PUBLISH_DATA_VOLUME_SIZE=50

...

2021-02-08T22:15:56.690-08:00 | [Container] 2021/02/09 06:15:55 Running command cargo make --env-file cargo.env
-- | --
  | 2021-02-08T22:15:56.690-08:00 | [cargo-make] INFO - cargo make 0.32.12
  | 2021-02-08T22:15:56.690-08:00 | [cargo-make] INFO - Build File: Makefile.toml
  | 2021-02-08T22:15:56.690-08:00 | [cargo-make] INFO - Task: default
  | 2021-02-08T22:15:56.690-08:00 | [cargo-make] INFO - Profile: development
  | 2021-02-08T22:15:56.690-08:00 | [cargo-make] INFO - Running Task: setup
  | 2021-02-08T22:15:56.690-08:00 | + cd /codebuild/output/src801399784/src/github.com/xxx/bottlerocket
  | 2021-02-08T22:15:56.690-08:00 | + mkdir -p /codebuild/output/src801399784/src/github.com/xxx/bottlerocket/build
  | 2021-02-08T22:15:56.690-08:00 | + mkdir -p /codebuild/output/src801399784/src/github.com/xxx/bottlerocket/build/images/x86_64-aws-k8s-1.17 <<<< see this?
  | 2021-02-08T22:15:56.690-08:00 | + mkdir -p /codebuild/output/src801399784/src/github.com/xxx/bottlerocket/build/rpms
  | 2021-02-08T22:15:56.690-08:00 | + mkdir -p /codebuild/output/src801399784/src/github.com/xxx/bottlerocket/.gomodcache
  | 2021-02-08T22:15:56.690-08:00 | [cargo-make] INFO - Running Task: setup-build
  | 2021-02-08T22:15:56.690-08:00 | + cd /codebuild/output/src801399784/src/github.com/xxx/bottlerocket
...

+ [ -L /codebuild/output/src801399784/src/github.com/xxx/bottlerocket/build/images/x86_64-aws-k8s-1.17/latest/bottlerocket-aws-k8s-1.17-x86_64* ]  <<< you can see here the wrong variant is being used for example
--
...

What are we doing wrong?

**Comment by tjkirch** [comment]
You're not doing anything wrong, but unfortunately we haven't gotten this to work.  So far we haven't found how to use cargo-make in any better way that allows clear usage of layered build variables.  We've hit a few things that seem like weaknesses.

We had to work around the way that cargo-make sets variables in Makefile.toml so that we could allow referencing variables that were overridden on the command line in later variable definitions.  If you look at [env.development](https://github.com/bottlerocket-os/bottlerocket/blob/16b868b1e84260507f37514d84beb3147e7c4733/Makefile.toml#L81) you'll see that we place variables there if they need to reference a variable that can be specified on the command line.  For example, `BUILDSYS_OUTPUT_DIR` depends on `BUILDSYS_VARIANT`, and we allow the user to override `BUILDSYS_VARIANT`.  If `BUILDSYS_OUTPUT_DIR` had been in the top-level `[env]` section, it wouldn't take the override.

This also means we've only been able to have _one_ level of variable references, and the user can't override the variables in `env.development`, because cargo-make only offers global (`[env]`) variables and one profile like "development," not arbitrary levels.  In places where we _have_ to have two levels of reference, we can no longer allow the user to override any of the variables, which is unfortunately the case with ones like `BUILDSYS_RELEASE_CONFIG_PATH`.

And, similarly, it means things like environment files don't work the way you'd expect, because there's an [order](https://sagiegurari.github.io/cargo-make/#usage-env-vars-loading-order) that doesn't match our needs; in the env file example, the file is loaded before anything else, and then its variables are overridden.

I'm hopeful that we can find another way to organize the variables, or another way to use cargo-make, to make these types of use cases possible.

**Comment by diranged** [comment]
Yikes - well thank you for the clear explanation at least! I think the BUILDING docs could use a blurb about this just so that people don't go down the wrong path trying to figure out how to make this work. I know that your examples in there are all correct, but I spent a while today trying to do it "better" and was surprised when it wasn't working. It would be interesting to get the cargo-make developers take on this...

**Comment by gregdek** [comment]
It's pretty clear that there are some weird issues around cargo make generally, and I believe it's the team's intention to replace it as soon as is practical. Rather that going down the road of documenting edge cases, it seems like it's better to leave this be and focus on pullling cargo make out entirely. Thanks for reporting it!
