### ISSUE TITLE
only build the packages needed for the current variant

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/bottlerocket#1361]
**What I'd like:**

We have a build-packages phase that builds all packages, even those that aren't needed for the variant currently being built. See if we can build only the packages that we need for the current variant.

**Any alternatives you've considered:**

Leaving it the way it is... but this becomes more problematic as we have more large packages (multiple kubernetes versions, or kernels, for example).

**Comment by bcressey** [comment]
One difficulty here is that the "packages" we include in a variant definition can be sub-packages at the RPM spec level. For example, the k8s variants now include "static-pods" which is a sub-package of `packages/os/os.spec`.

This property is useful at image construction time, since we can easily create a list of specific RPM packages to install. However, for the purposes of limiting the build to just the packages that we need, it implies a need to expand our spec file parsing to account for potential package outputs.

**Comment by webern** [comment]
Yeah, and I think the other problem is release.spec which expects all of it's RPMs to be exist? For a proof of concept I'm thinking of hacking Cargo.toml`[dependencies]` to invoke cargo build on all prerequisites before arriving at the 'cumulative' specs.
