### ISSUE TITLE
host-containers fails when any expected field is missing

### ISSUE THREAD

**Issue by samuelkarp** [bottlerocket-os/bottlerocket#1385]
**Image I'm using:**
```
bash-5.0# cat /etc/os-release
NAME=Bottlerocket
ID=bottlerocket
PRETTY_NAME="Bottlerocket OS 1.0.6"
VARIANT_ID=aws-ecs-1
VERSION_ID=1.0.6
BUILD_ID=ee56d1fc
```

**What I expected to happen:**
When I reboot a working Bottlerocket instance in a non-degraded state, it comes back up in non-degraded state.

**What actually happened:**
Bottlerocket booted in a degraded state where the `settings-applier.service` unit failed, causing `configured.target` to fail and any other units depending on it to fail.

**How to reproduce the problem:**

1. Make a typo when adding a host-container setting such that you have an unintended container entry like "admiin"
2. Ensure that the "admiin" container is missing at least one required field like "source" or "superpowered"
3. Ensure that the "admiin" container is disabled
4. Reboot

**Possible approaches to fix this:**

1. The settings API should enable us to delete mistaken host-container entries
2. The model should enforce that all required fields are actually present when creating host-container settings
3. The `host-containers` binary should tolerate missing fields, especially when a given host-container entry is not enabled

**Comment by webern** [comment]
> it comes back up in non-degraded state.

I think that's a typo.

**Comment by tjkirch** [comment]
I think we probably want to take all 3 approaches, to some degree.

For (1) we should be able to delete settings from a map, yeah.  We need to figure out what happens when that's done in "bad" situations, like trying to delete just _one_ of the settings needed for a host container, i.e. this issue ;)

For (2) we should probably have some ability to link or verify settings together somehow, though today's serialization/deserialization treats structs as just levels, not groupings, so it'll need some thought.

For (3) we should consider where our services are missing some needed tolerance for errors.  host-containers could treat missing "enabled" as false, for example, but should probably still fail if the container definition is missing a source.  ("fail" is up for debate; it could continue with other containers, or stop; it could fail the systemd service, or not; etc.)

**Comment by bcressey** [comment]
We should probably have reasonable defaults for host containers - "enabled: false" and "superpowered: false" both seem sensible.

**Comment by etungsten** [comment]
> I think we probably want to take all 3 approaches, to some degree.
> 
> For (1) we should be able to delete settings from a map, yeah. We need to figure out what happens when that's done in "bad" situations, like trying to delete just _one_ of the settings needed for a host container, i.e. this issue ;)
> 
> For (2) we should probably have some ability to link or verify settings together somehow, though today's serialization/deserialization treats structs as just levels, not groupings, so it'll need some thought.
> 
> For (3) we should consider where our services are missing some needed tolerance for errors. host-containers could treat missing "enabled" as false, for example, but should probably still fail if the container definition is missing a source. ("fail" is up for debate; it could continue with other containers, or stop; it could fail the systemd service, or not; etc.)

I believe #1580 addresses (3).
I'll go ahead and create separate issues for 1) and 2).
