### ISSUE TITLE
Journal is recreated with a different machine ID after reboot on ARM

### ISSUE THREAD

**Issue by arnaldo2792** [bottlerocket-os/bottlerocket#1493]
**Image I'm using:**
Bottlerocket 1.0.8 aarch64

**What I expected to happen:**
I expect that logs for every reboot are appended to the existing journalctl log file, so when I run `journalctl --list-boots`, the command should show entries for previous boots.

**What actually happened:**
`journalctl --list-boots` only shows one single entry after reboots and `ls -latr /var/log/journal` shows:

```sh
total 28
drwxr-sr-x. 2 root systemd-journal 4096 Apr 15 22:07 78a1c8fe2aa44b0984ebdbe4cf1f5570
drwxr-xr-x. 4 root root            4096 Apr 15 22:07 ..
drwxr-sr-x. 2 root systemd-journal 4096 Apr 15 22:08 ffb7c37dff4a461f8e8cd96a8bd5e5c2
drwxr-sr-x. 4 root systemd-journal 4096 Apr 15 22:08 .
```

**How to reproduce the problem:**
* Launch any aarch64 Bottlerocket instance
* Reboot
* Enter the host through `sudo sheltie` and run `journalctl --list-boots`, it will show only one instead of two

**Comment by bcressey** [comment]
We're meant to get the machine ID from KVM on arm64 instances, but [we're not detecting KVM](https://github.com/systemd/systemd-stable/blob/v247-stable/src/core/machine-id-setup.c#L63).

x86 likely works because it can use [detect_vm_cpuid](https://github.com/systemd/systemd-stable/blob/937118a5b2f27a7913c421ad76893cdda01c5566/src/basic/virt.c#L42).

One approach would be to apply EC2-specific knowledge to [detect_vm_dmi](https://github.com/systemd/systemd-stable/blob/937118a5b2f27a7913c421ad76893cdda01c5566/src/basic/virt.c#L136) and match "Amazon EC2" to KVM. This might have to be conditional for arm64 if those `/sys/class/dmi/id` values are present under Xen.
