### ISSUE TITLE
Provide options for format and use external disks

### ISSUE THREAD

**Issue by vikas027** [bottlerocket-os/bottlerocket#1563]
**What I'd like:**
The official bottlerocket AMI on AWS comes with a 20 GB volume. Even if bump up the volume size in the launch template, the allocatable storage is still around 20 GB.

In this example, a 200 GB disk is used which is seen by the OS but can't be allocated.

```
$ kubectl describe no <node_name>
<redacted>
﻿Capacity:
  attachable-volumes-aws-ebs:  25
  cpu:                         2
  ephemeral-storage:           20624592Ki
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      7844784Ki
  pods:                        29
Allocatable:
  attachable-volumes-aws-ebs:  25
  cpu:                         1930m
  ephemeral-storage:           17933882132
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      7154608Ki
  pods:                        29
```

**Any alternatives you've considered:**
None as of now.

**Comment by etungsten** [comment]
Hi @vikas027, thanks for reaching out! Can you check if you’re bumping the 20GB volume in your launch template or the 2 GB root volume (`/dev/xvda`)? Bumping the 20GB volume in your launch template should work as Bottlerocket would expand the partition to fill the entire volume. Bumping the 2GB volume would not do anything since that’s used to store Bottlerocket images and we don’t allocate any more space beyond 2GB. 

I was able to bump the size of my secondary volume from 20GB to 200GB at launch time and it was fully allocated:

```
$ kubectl describe node <node-name>
...
Capacity:
  attachable-volumes-aws-ebs:  25
  cpu:                         2
  ephemeral-storage:           206412008Ki
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      7833556Ki
  pods:                        29
Allocatable:
  attachable-volumes-aws-ebs:  25
  cpu:                         1930m
  ephemeral-storage:           189155564434
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      7143380Ki
  pods:                        29
```

If you’d like to provide more storage for your container workloads through other means, I suggest deploying the [EBS CSI driver](https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html) to dynamically provision EBS volumes for your pods.

**Comment by vikas027** [comment]
Thanks, @etungsten . That helped, I didn't noticed that bottlerocket AMI comes with two disks.
