### ISSUE TITLE
Add support for ECS Exec

### ISSUE THREAD

**Issue by mifisignal** [bottlerocket-os/bottlerocket#1649]
ECS Exec is an important feature of ECS. It allows customers to obtain a shell in the context of a running container (à la `kubectl exec`), without requiring admin access to the host. 

Currently, ECS Exec is supported on the Amazon Linux 2-based ECS optimized AMI and similar variants, but is not supported on Bottlerocket. Given ECS Exec's popularity, it makes sense to add support for it in Bottlerocket as well.

**Comment by zmrow** [comment]
Thanks for the request - we'll look into it!

**Comment by ghost** [comment]
+1 with some fluff text context! We use ECS Exec to perform a lot of tasks from debugging to maintenance across our containers. We have multiple types of Operating Systems we use and all but Bottlerocket supports this feature. I would love to finally switch all the remaining Operating Systems we use to Bottlerocket for all the lovely benefits it brings but I can't complete that migration until this feature exists. Would love to see this happen!

**Comment by arnaldo2792** [comment]
I was curious about what will be required in Bottlerocket in order to support this feature. I found out that the ECS agent [will mount] SSM binaries provided by the host, which I assume are statically linked.

[will mount]: https://github.com/aws/amazon-ecs-agent/blob/2ddc8596a2dd873d4b7b5b0cb364ab3eb6affcd5/agent/engine/execcmd/manager_init_task_linux.go#L164

**Comment by ryansch** [comment]
I just hit my head on this. Unfortunately it seems that there's no error surfaced anywhere when a task can't be scheduled because of this requirement.

**Comment by stmcginnis** [comment]
@dmitmasy fyi for your awareness and prioritization.
