### ISSUE TITLE
Is ftp.pcre.org dead?

### ISSUE THREAD

**Issue by vezaynk** [bottlerocket-os/bottlerocket#1837]
Hi!

I'm not a user of bottlerocket. I was brought here by searching for projects depending on `https://ftp.pcre.org/pub/pcre`. The reason being that that website seems to be down, and not just for me, and not just now.

![image](https://user-images.githubusercontent.com/10255546/142737406-005c7ea1-be1a-4d95-8f31-04d9165a4cda.png)

Further evidence is that the [PCRE website](https://webcache.googleusercontent.com/search?q=cache:JsPEKJLHvmUJ:https://www.pcre.org/+&cd=1&hl=en&ct=clnk&gl=ca) says as much: 

> Note that the former ftp.pcre.org FTP site is no longer available. You will need to update any scripts that download PCRE source code to download via HTTPS, Git, or Subversion from the new home on GitHub instead.

Now to my question -- why is [this project referencing a dead link](https://github.com/bottlerocket-os/bottlerocket/blob/6d684f8436a60cd6be418b9f46e063168cd9e267/packages/libpcre/Cargo.toml#L15), and more importantly, how does it build without it?

It doesn't seem to be a legacy thing either, as the PCRE link was last updated 5 months ago, long after ftp.pcre.org had been discontinued.

**Comment by tjkirch** [comment]
Thanks for the tip!  It looks like we'll have to update our package to reference the new location.

> how does it build without it?

https://github.com/bottlerocket-os/bottlerocket/blob/328b50aa489bd6c7d386ea7ad0790ec39d2a9ca9/tools/buildsys/src/cache.rs#L23

When actually building Bottlerocket, we fetch sources from a cache we host at the bottlerocket domain.  That helps prevent scenarios exactly like this, and reduces the load we put on upstream projects' resources.  That's why we hadn't noticed.  We would notice the next time we saw a PCRE update and tried to download the original from the dead domain, but otherwise things would flow smoothly.

**Comment by vezaynk** [comment]
@tjkirch Interesting, thanks for your reply.

I'm trying to get to the bottom of this because it making some of my local builds (Once again, completely unrelated to bottlerocket) fail because seemingly thousands of programs on Github seem to depend upon the non-existant FTP server.

It makes me feel insane because seemingly nobody else is reporting issues related to it. I found (and since lost) evidence pointing  to the idea that the ftp server was shut-off many years ago and yet I find projects like yours that update urls pointing to it merely 5 months ago, implying that it was still accessible.

I'm tempted to write a bot PR'ing every single repository updating the reference to `https://ftp.exim.org/pub/pcre/` which looks like a working mirror of it, but doing so would be improper without first getting to the bottom of when exactly did it go offline and why so many projects still depend on it.

Any further context you could give would be appreciated.

Thanks!

**Comment by tjkirch** [comment]
> Any further context you could give would be appreciated.

I don't have an exact history of commands, but I can almost guarantee that when I updated pcre 5 months ago, I downloaded the archive using the ftp.pcre.org URL in the file you saw, just because that's my workflow and I've been doing it that way for a while.  So, I'm equally almost positive that the URL worked at that time.  I'm not sure why it would have been any different for others.  I can only guess that the deprecation of the URL was a "soft" deprecation, where notices were added and links changed, while the site was actually left up a while longer...

**Comment by bcressey** [comment]
Based on the Wayback Machine's results, the `ftp.pcre.org` URL was removed from the main site between [August 21, 2021](https://web.archive.org/web/20210821201522/https://pcre.org/) and [August 25, 2021](https://web.archive.org/web/20210825214354/https://pcre.org/), with the deprecation notice added.

Someone seems to have run into the issue in Buildroot [yesterday](https://lore.kernel.org/all/47a68b89-d935-59f3-b051-c60c3e2d33d1@armadeus.com/T/) so it's possible that the site's been up until _very_ recently.

**Comment by vezaynk** [comment]
Good find! I wrote an email to the pcre.org webmaster to see if they would be willing to add a redirect from their ftp.pcre.org to ftp.exim.org to mitigate the breakage.

![image](https://user-images.githubusercontent.com/10255546/142751532-e019df12-8619-4d5d-8082-224c9a32c870.png)


Thanks for your insights.

**Comment by tjkirch** [comment]
I'm going to reopen this so we can update our links :)
