### ISSUE TITLE
Failure on First boot of VMWARE k8s v1.21 built from source commit 78331de8496350ee6a8573ea3938cd10f1a065e4

### ISSUE THREAD

**Issue by trebonian** [bottlerocket-os/bottlerocket#1879]
This appears to fail on First boot of a k8s worker node (on variant vmware-k8s-1.21) very early when running Sundog. It appears some default metadata keys are not initialized. It could be a build issue - but I don't know how to inspect the image for where the default metadata keys are stored. This build is a very late commit 1.5.0. It's not easy to get any more details this early in the boot process. Is there any debugging or traceing options I can turn on for more clarity?

![image](https://user-images.githubusercontent.com/11244/146655485-cd0bf7d9-e650-4531-a897-6ff4524b7e1c.png)

**Comment by bcressey** [comment]
Some background on what's happening here, in case it sheds any light.

On initial boot, Bottlerocket has two phases for bootstrapping into the initial settings. The first phase is to retrieve them from the platform-specific metadata source - IMDS on EC2, guestinfo on ESXi. The second phase is to run "setting generators" to generate settings where a default can be worked out from runtime values. `sundog` is the helper program that handles invoking the setting generator programs.

The VMware model includes these generators:
```
❯ rg -L generator sources/models/src/vmware-k8s-1.21
sources/models/src/vmware-k8s-1.21/defaults.d/50-kubernetes-vmware.toml
10:node-ip.setting-generator = "netdog node-ip"

sources/models/src/vmware-k8s-1.21/defaults.d/10-defaults.toml
46:setting-generator = "schnauzer settings.updates.metadata-base-url"
59:seed.setting-generator = "bork seed"
85:setting-generator = "netdog generate-hostname"
```

Which is why you're seeing the query for those 4 settings, specifically - `sundog` is trying to work out if any of those settings already have a value, in which case it would skip calling that generator program.

It's the API request that `sundog` is making to collect those values that's failing [here]( https://github.com/bottlerocket-os/bottlerocket/blob/78331de8496350ee6a8573ea3938cd10f1a065e4/sources/api/apiserver/src/server/controller.rs#L291). Essentially the error is that we're expecting to deserialize a JSON value back into a known struct, but we reach EOF before we get a complete value.

That suggests two possibilities based on the observed failure mode. We might've accepted a value from user-data settings and serialized it to the datastore, but aren't able to deserialize it. Or somehow an invalid JSON value might have been written directly to the datastore in `/var/lib/bottlerocket` - maybe the file wasn't fully written before we attempted to read it again.

***
The first thing to check is to see whether you're specifying any of these values via user-data:
```
[settings]
kubernetes.node-ip = "..."
network.hostname = "..."
updates.seed = "..."
updates.metadata-base-url = "..."
```

If so, then remove that setting and see if first boot happens correctly. You can then attempt to reapply the value via `apiclient set` on a running system; it might still fail but you'd be in an easier position to debug by inspecting the file written to `/var/lib/bottlerocket`.

If you're not setting any of those values, then it's a puzzle - since the files that the API server ends up reading shouldn't even exist.

When I have to debug something gnarly like that, I make some [local edits](https://gist.github.com/bcressey/ab49a8277e0a6eb080befb518ab2cc0e) to include a shell in the image and to make sure it activates in the "preconfigured" phase when the settings changes are happening. (You'll have to run `cargo update` in the `variants` directory after making the change; then the next build will include the new packages.)

You should still see the same error on the console at boot, but this time you'll be able to enter whatever at the `login` prompt and drop into a root shell.

**Comment by trebonian** [comment]
Thanks for the prompt reply.

You have confirmed what I had analyzed, and was trying to figure out how to install a shell and look at the settings  repo loaded by the userdata.

You helpfully provided my a patch to do so.

Thanks. I will confirm if the error is on my side or if it is a bug. I did have a setting for hostname, but none others.

I checked the strings in storewolf for the settings that were defaulted but they looked ok from a static point of view.

I will get back soon.


Barry Silverman
Cell: 416-407-8091
DID: 647-547-0302
Voice: 416-368-7677 x234
Disus Inc. - 30 Wellington St W.,5th Floor
Toronto, Ontario , M5L 1E2 Canada
Email: ***@***.***
________________________________

**Comment by trebonian** [comment]
I think the issue is on my side. I built a version with the console, and without changing anything else, it got past the sundog problem. Perhaps I had a stale RPM from an older build..

I do have a an issue with the console patch - it opens two shells pointing to /dev/console, and /dev/tty1 - and it eats characters from both processes.

How do I configure the console to only use 1 console device?

Otherwise, I think you can close the issue...

Thanks again for the help - it was extremely useful..

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
