### ISSUE TITLE
Access to the path '/proc/7/map_files' is denied. ---> System.IO.IOException: Permission denied

### ISSUE THREAD

**Issue by Eslam-mohammed-anwar** [bottlerocket-os/bottlerocket#1887]
**Image I'm using:**
 we just updated AMI from ami-091acde69d56082b9 (1.3) to ami-003c8cac51a7c66fe (1.5.1) and some of the containers started to report this logs 

Unhandled Exception: System.UnauthorizedAccessException: Access to the path '/proc/7/map_files' is denied. ---> System.IO.IOException: Permission denied

This is .net core containers and we enabled the OCI hooks to mitigate the log4j vulnerabilities

**Comment by arnaldo2792** [comment]
Hi! Thanks for bringing this to our attention. Could you please check if the error appears when you disable the log4j hot patch?, this will help us narrow down the problem to the OCI hook itself, instead of a permissions problem related to the SELinux Policy. Also, are you running any monitoring tool inside your workload pod? It looks like the process logging out the error tried to read a memory mapped filed for a privileged process, and the reading process might not have access to the privileged file.

**Comment by cbgbt** [comment]
Something else that might be helpful to have here is the base container image. is it [this one?](https://hub.docker.com/_/microsoft-dotnet) We'll have a hard time reproducing this without a bit more information. I'll close this for now, but please feel free to re-open this with more detail.
