### ISSUE TITLE
Support insecure registries

### ISSUE THREAD

**Issue by jpculp** [bottlerocket-os/bottlerocket#1950]
**What I'd like:**
Bottlerocket doesn't support insecure registries. Should we add a setting to configure them?

### Discussed in https://github.com/bottlerocket-os/bottlerocket/discussions/1922

<div type='discussions-op-text'>

<sup>Originally posted by **exolain** January 24, 2022</sup>
Hi all,

I was wondering, what is the best way to configure the "insecure-registries" setting that it would be done via /etc/docker/daemon.json configuration file?  But using the bottlerocket settings ? I was checking the settings.container-registry.mirrors setting, but it seems to be it only allows https* endpoints.
Thanks!</div>

**Comment by cbgbt** [comment]
For now, I think we'd like to avoid supporting insecure registries, since it can easily lead to cluster configurations that are insecure.

Based on some discussion in #1922, It seems like this is commonly desired for registries which are self-hosted within the cluster. There are a few mechanisms for supporting SSL certificate signing and management in clusters. If you're looking to enable insecure registry support, I'd suggest:

* Checking the user guide for your software to determine if there is existing guidance for enabling TLS communication to its registries.
* Or, using something like [cert-manager](https://cert-manager.io/) (which supports multiple CAs, including self-signed certs) to manage certificates for the software hosted in your cluster.

Of course,if this isn't possible or there are other use-cases that I'm missing, feel free to re-open this or create a new issue. Thanks!
