### ISSUE TITLE
Add support for Linux Kernel 5.15 LTS

### ISSUE THREAD

**Issue by AhmadMasry** [bottlerocket-os/bottlerocket#2008]
Please add support for Linux Kernel 5.15 LTS to support newer hardware and to include the new features included in the newer kernel.

**Comment by etungsten** [comment]
Hi @AhmadMasry, thanks for reaching out. We're planning to move the 5.15 kernel for all new variants that are going to be released this year, starting with the `*-k8s-1.23` variants in ~May.

**Comment by AhmadMasry** [comment]
Hi @arnaldo2792 and @etungsten 
I just upgraded to EKS 1.23 and updated my managed node group to 1.9.0 and the kernel is still 5.10.130.
Is there any bootstrap options needed to use the newer kernels?

**Comment by etungsten** [comment]
Hi @AhmadMasry,

I'm really sorry about this! The K8s 1.23 variants shipped in v1.8.0 with the 5.10 kernel, since the 5.15 kernel wasn't quite ready yet. The current plan is for all new variants from the 1.9.0 release onwards to use the 5.15 kernel. The first K8s variants to ship with the 5.15 kernel should be `*-k8s-1.24` variants hopefully sometime later this year.

**Comment by munjalpatel** [comment]
@etungsten any plans to move to kernel 5.18 instead of 5.15 now that it's out?

5.18 will allow us to start leveraging BBR congestion control for Pods
https://docs.cilium.io/en/v1.12/operations/performance/tuning/#bbr-congestion-control-for-pods

**Comment by etungsten** [comment]
Hi @munjalpatel, we currently don't have any immediate plans to add another kernel to the mix. It is possible a new LTS kernel will appear for newer variants towards the end of 2023.
