### ISSUE TITLE
tools: unpin or update tokio

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/bottlerocket#2153]
We should consider unpinning tokio in the tools workspace. Pinning tokio in bottlerocket makes sense given the level of confidence we want to have in bottlerocket's behavior. But for our publishing and builds tools, perhaps we don't need to be as strict.

In any event `~1.8` is incompatible with the new `testsys` CLI and blocks #2147 and #2148 (and the rest of `cargo make test`) because kube-rs has `tokio = 1.14` in its Cargo.toml.

Note: I believe that getting us updated to 1.14 or better will require updating tough-ssm, tough-kms and coldsnap (because we stopped pinning tokio in those libs recently)

**Comment by cbgbt** [comment]
It seems like tokio `1.14.x` stops being supported this month (6/2022). I've started a discussion to see if there will be a new version dedicated as LTS: https://github.com/tokio-rs/tokio/discussions/4732

**Comment by webern** [comment]
For the tools workspace I recommend that we use tokio = "1" and cargo update to latest in our lock file. I don't think we need to pin the tools workspace like we do for sources.

**Comment by cbgbt** [comment]
I am definitely conflating issues which are actually tangential:
* I agree that we don't need to pin the tools repo
* We should move anything pinned to the 1.8 LTS release to the newest LTS, since 1.8 is no longer supported.

tokio has marked `1.18` as the next LTS in https://github.com/tokio-rs/tokio/pull/4733, and plans to support that until January 2023.
