### ISSUE TITLE
Metal: Expand server hardware compatibility

### ISSUE THREAD

**Issue by zmrow** [bottlerocket-os/bottlerocket#2246]
For our metal variants, we should greatly expand our hardware compatibility.  Ideally, we would support all main classes of server hardware.

**Comment by foersleo** [comment]
First need to split out the metal specific parts so we keep track of what went in for metal specifically (Issue https://github.com/bottlerocket-os/bottlerocket/issues/2211).

**Comment by foersleo** [comment]
I have been working towards this and checked what we are currently missing, mostly in the storage and networking side.

We are currently mostly missing support for some 10G+ networking equipment by various vendors. (https://github.com/bottlerocket-os/bottlerocket/issues/2361 is referring to one of the missing device series we are missing).

There is some features that are supported by multiple devices where we can have a discussion if those are necessary for Bottlerocket use cases and enable them for all supporting devices (i.e. DCB).

**Comment by foersleo** [comment]
There is some additional planning work that needs to happen here.
We so far have worked towards enabling what I'd call modern common server hardware  (standard RAID controllers and 10G+ Ethernet NICs). However, it is not quite clear if that is the actual boundaries where we want to stop at for the bare metal variant.

Some of the questions that need to be discussed:

- [ ] Where are the boundaries of expanding HW compatibility?
- [ ] What do people need in that regard? What does the community want?
- [ ] What level of support and/or maintainership can we offer for what kind of HW?
- [ ] How can we standardize testing so that we can reason about compatibility for each version?
- [ ] How can we load share testing/verification for different platforms within the community? Who can contribute?
