### ISSUE TITLE
allow setting max_container_log_line_size for containerd

### ISSUE THREAD

**Issue by rubroboletus** [bottlerocket-os/bottlerocket#2292]
**What I'd like:**

It will be really nice, when we will be able to set max_container_log_line_size value for containerd.

**Any alternatives you've considered:**

**Comment by etungsten** [comment]
Hi @rubroboletus , thanks for opening this issue. We'll take a look into supporting that.

**Comment by stmcginnis** [comment]
Looking at this now.

Since we may some day want to switch out our runtime from containerd to something else, we should keep these settings somewhat runtime agnostic, even if the specific setting is only applicable to containerd.

I am looking at adding:

* `settings.container-runtime.max-container-log-line-size`: Controls how long container log messages can be.
  If the log output is longer than the limit, the log message will be broken into multiple lines.
* `settings.container-runtime.max-concurrent-downloads`: Restricts the number of concurrent downloads for each image.

Testing out changes locally now. Will push up a PR soon.
