### ISSUE TITLE
QUESTION: do workloads drain automatically if running in EKS and using SPOT instances?

### ISSUE THREAD

**Issue by jobcespedes** [bottlerocket-os/bottlerocket#2453]
Do workloads drain automatically if running in EKS and using SPOT instances?
I found `settings.ecs.enable-spot-instance-draining` ( from https://github.com/bottlerocket-os/bottlerocket/pull/1100 by @mkulke) in the documentation but I am not sure it should be set for EKS or just ECS. In addition it made me wonder if draining is already done in EKS for spot instances. Thanks

**Comment by arnaldo2792** [comment]
Hello there! Sorry for the late response.

>  I found settings.ecs.enable-spot-instance-draining

Configurations within the `ecs` key will only work for ECS images. If you try to set it through user data your k8s hosts won't be able to boot since the configuration doesn't exist in the API model for k8s images. On the other hand, if you try to use `apiclient` you will get an error saying that the key `ecs` is an invalid key.

> In addition it made me wonder if draining is already done in EKS for spot instances

It seems like there is already some guides to use EC2 spot instances in EKS:

https://aws.amazon.com/premiumsupport/knowledge-center/eks-spot-instance-best-practices/

**Comment by jobcespedes** [comment]
Thanks for your reply. It is now clear for me the option is only for ECS. 

It was my understanding that draining is done out of the box with EKS + managed groups, since [managed node groups doc](https://docs.aws.amazon.com/eks/latest/userguide/managed-node-groups.html ) says so. I just wanted to make sure it remains the same when using Bottlerocket (EKS + managed groups + Bottlerocket). Seeing `settings.ecs.enable-spot-instance-draining` made me hesitate and considered asking here.

**Comment by arnaldo2792** [comment]
Yes! Bottlerocket does support the features offered by managed node groups :+1: (we try to keep feature parity with what the EKS optimized AMI)
