### ISSUE TITLE
Enabling kubelet client certificate rotation

### ISSUE THREAD

**Issue by dusanu87** [bottlerocket-os/bottlerocket#2492]
We have a running AWS EKS cluster version _1.22_ with Bottlerocket _v1.9.1_. 
We would like to check is it safe/supported to enable kubelet certificate rotation by passing kubelet extra arg _--rotate-certificates_ ? This question is actually related to Bottlerocket _v1.10.0_ for EKS version _1.23_ since we are going to upgrade EKS cluster.
We are mainly asking because of the current setup and implementation since we are using EKS managed nodes with BottlerocketOS. Could this change cause some issues in the cluster?

**Comment by bcressey** [comment]
Client certificates are not used to authenticate an EC2 worker node to an EKS cluster; the instance IAM role is used along with the node identity.

The kubelet also has a server certificate (for serving `kubectl logs` and `kubectl exec`) and the default kubelet config enables the `RotateKubeletServerCertificate` feature gate so that this certificate is rotated.

Consequently you shouldn't need to configure this particular flag.

Also FYI, when you upgrade your cluster and then upgrade your managed node group, the underlying worker nodes will be replaced with ones running the AMI that has kubelet 1.23 baked in. Effectively this will "rotate" the node certificates by rotating the entire node.
