### ISSUE TITLE
Increase bootstrap containers permissions

### ISSUE THREAD

**Issue by raulsh** [bottlerocket-os/bottlerocket#2652]
**What I'd like:**

- Execute actions like modprobe or service startup inside a bootstrap container

**Any alternatives you've considered:**

I tried a lot of forms to do a modprobe. Executing sheltie inside a bootstrap container with:
- modprobe XXXX
- systemctl start modprobe@XXXX.service
- Modifying filesystem (impossible because it's Read-Only)

But the output is always "Operation Not Permitted". I guess it must be some SELinux restriction.

Works well inside a host container, but host container doesn't have "essential" param. So if the actions fails, the node boots 
without problems. In my case, I want to activate ip_vs_sed to use it with ipvs, so if the module activation fails, I will not be able to use ipvs and I will never be able to handle this err.

**Comment by arnaldo2792** [comment]
Hello! There is an API that you can use to load/bloack kernel modules:

```toml
# Load the kernel module
[settings.kernel.modules.sctp]
allowed = true
# Block the kernel module
[settings.kernel.modules.udf]
allowed = false
```

That will load the `sctp` kernel module in the next boot, if you applied the settings after the initial boot. However, if you configure the kernel modules in user data while launching your instances no reboot is required. Please let us know if the API exposed doesn't meet your requirements.

FWIW, you are getting the `Operation Not Permitted` error because bootstrap containers don't have `CAP_SYS_MODULE`.

**Comment by raulsh** [comment]
I tried. It was my first attempt. But it didn't work. I will try again and send the logs.
