### ISSUE TITLE
Some way to monitor network interface metrics

### ISSUE THREAD

**Issue by gbucknel** [bottlerocket-os/bottlerocket#2794]
**What I'd like:**
I'm trying to figure out if my nodes are subject to DNS throttling. 
The nodes (m5a.4xlarge) seem to be running the ENA network adapter and so looking at the `linklocal_allowance_exceeded` metric looks like a very promising way to do this (option 3 here -> https://aws.amazon.com/premiumsupport/knowledge-center/vpc-find-cause-of-failed-dns-queries/) 

However, Bottlerocket doesn't seem to have ethtool in it. I've looked around in the /sys filesystem from the sheltie shell (/sys/class/net/eth0/statistics) , but that metric isn't there and I'm not sure if it lives somewhere else?

I'm running EKS 1.23 , Bottlerocket OS 1.12.0 (aws-k8s-1.23)

**Any alternatives you've considered:**
I'm not sure if this is a very "bottlerocket-ey" solution to the problem, perhaps there is a better way to get these metrics that I'm not familiar with (some sort of native Prometheus metric would be great). 

This doc suggests using a ethtool daemonset https://aws.github.io/aws-eks-best-practices/networking/CoreDNS/ , but it looks like it won't work if ethtool isn't on the node: 

https://github.com/drdivano/prometheus-ethtool-exporter/blob/master/ethtool-exporter.py#L112-L113

**Comment by mchaker** [comment]
Hi @gbucknel, thanks for reaching out. I'm looking into this.

**Comment by yeazelm** [comment]
Thanks for filing this issue @gbucknel ! I believe you should be able to use the [Admin container](https://github.com/bottlerocket-os/bottlerocket#admin-container) to get these metrics. The default Admin container is Amazon Linux 2 which has `ethtool` in the repo. So installing via `yum install ethtool` and then running `ethtool -S eth0` should yield the data you are looking for. Let us know if that works or not for you. 

For what it's worth, `ethtool` does make sense to have in the host OS since it can be useful for lots of debugging like you found. I will also investigate adding it to the OS so it will be there in the future.

**Comment by gbucknel** [comment]
thanks @yeazelm ! I'll try the admin container (I never think of using it). 
Should I leave the issue open for adding `ethtool` to the host OS?

**Comment by yeazelm** [comment]
Let's leave this open for the `ethtool` work. Glad that got you unblocked!

**Comment by arnaldo2792** [comment]
I looked at what is needed to add `ethtool`, it doesn't have a whole lot of dependencies. I think this is a good first issue for new contributors

**Comment by yeazelm** [comment]
I just merged the ethtool PR so it should be in the next release!

**Comment by gbucknel** [comment]
@yeazelm legend! thank you!
