### ISSUE TITLE
Denial Of Service vulnerability discovered in Golang. (CVE-2022-27664) in vpc-cni plugins

### ISSUE THREAD

**Issue by gaborho** [bottlerocket-os/bottlerocket#2840]
Our cloud security platform discovered "Denial Of Service vulnerability discovered in Golang. (https://github.com/advisories/GHSA-69cg-p879-7622)" in our Bottlerocket OS based EKS worker nodes. Please see the affected packages below.
We believe those cni-plugins are part of vpc-cni addon, and are from upstream, sourced during build process here:
https://github.com/bottlerocket-os/bottlerocket/blob/develop/packages/cni-plugins/Cargo.toml#L15

Please advise how to patch that vulnerability.

**Image I'm using:**
Bottlerocket OS 1.12.0 (aws-k8s-1.24)
ami-074a4bb01233b773b
bottlerocket-aws-k8s-1.24-x86_64-v1.12.0-6ef1139f

**What I expected to happen:**
Packages are not vulnerable.

**What actually happened:**
Packages are vulnerable.

**How to reproduce the problem:**
Case #1 vpc-cni plugin v1.11.4-eksbuild.1

SSM to Bottlerocket control container, then entering to admin container with enter-admin-container command, then go into Bottlerocket host's root fs using 'sheltie' command.
Then cd to /var/lib/cni-plugins/.overlay/upper/

then use command:

grep -ai 'go1.' aws-cni -> go1.18.3 (non-vulnerable)

grep -ai 'go1.' bandwidth -> go1.17.7 (vulnerable)
grep -ai 'go1.' portmap -> go1.17.7 (vulnerable)
grep -ai 'go1.' loopback -> go1.17.7 (vulnerable)

===

Case #2 vpc-cni plugin v1.12.2-eksbuild.1

grep -ai 'go1.' aws-cni -> go1.19.2 (non-vulnerable)

grep -ai 'go1.' bandwidth -> go1.17.7 (vulnerable)
grep -ai 'go1.' portmap -> go1.17.7 (vulnerable) 
grep -ai 'go1.' loopback -> go1.17.7 (vulnerable)
grep -ai 'go1.' host-local -> go1.17.7 (vulnerable)

**Comment by stmcginnis** [comment]
Hi @gaborho - thanks for reporting this.

This is something that is pulled in to an EKS node at runtime. So https://github.com/aws/amazon-vpc-cni-k8s/issues/2292 is the right route to go to track this.

In the meantime, you may be able to get around this by [updating your VPC CNI plugin](https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html).

Since this is a runtime result from EKS and not something that is prepackaged in the Bottlerocket image itself I am going to close this issue since I don't believe their is any action that can be taken from the Bottlerocket project side for this. Feel free to reopen if I've missed something.
