### ISSUE TITLE
Why are `image-gc-high-threshold-percent` and `image-gc-low-threshold-percent` strings?

### ISSUE THREAD

**Issue by jonathan-innis** [bottlerocket-os/bottlerocket#2883]
**Image I'm using:**

`bottlerocket-aws-k8s-1.23-x86_64-v1.12.0-6ef1139f`

**What I expected to happen:**

The [kubeletConfiguration] defines these values as int32s in the spec so it's odd to me that these values would be expected to be strings in the current bottlerocket setting configuration. I imagine (due to breaking changes) this would be hard to fix now, but it's surprising behavior for someone who is coming from configuration the `kubelet-config.json` on something like an AL2 image.

**What actually happened:**

Bottlerocket fails to start if it's passed in the values as integers rather than strings

**How to reproduce the problem:**

[settings.kubernetes]
image-gc-high-threshold-percent = 85
image-gc-low-threshold-percent = 80

**Comment by yeazelm** [comment]
Thanks for submitting this issue @jonathan-innis! I have been digging a bit around on this and it looks like this is mostly due to Bottlerocket originally only supporting strings but we have added [support for scalar values](https://github.com/bottlerocket-os/bottlerocket/pull/2559) so it should be possible to convert these over.

> I imagine (due to breaking changes) this would be hard to fix now

We have been able to do some of these types of changes in the past, so it's not unreasonable to change this.

**Comment by jonathan-innis** [comment]
Thanks @yeazelm. Yeah, it seems like a weird opinionated stance to take. The current state certainly isn't a blocker; however, I do think that it should be properly documented somewhere in the BR repo (maybe in the README under the settings). This seems like a recurring issue that I've seen a few other people hit and I know that there is [already an issue opened in this repo](https://github.com/bottlerocket-os/bottlerocket/issues/2324) asking for this to be documented.

**Comment by webern** [comment]
I have opened a PR that attempts to remedy this situation. It allows these to be expressed as numbers and adds documentation to the README.

> a weird opinionated stance to take

It wasn't intentional. There were some implementation details in the code that caused us to do the wrong thing with these settings when they were added.

I looked through all of the settings and couldn't find any others that should be numbers instead of strings.
