### ISSUE TITLE
Deprecation of cgroup v1

### ISSUE THREAD

**Issue by hitsub2** [bottlerocket-os/bottlerocket#3018]
As per disucssion [#2874](https://github.com/bottlerocket-os/bottlerocket/discussions/2874) Bottlerocket 1.13.0 moving to cgroup v2 for new variants, I just want to check out if there is any clear date for deprecation and remove of cgroup v1 in BR.

### Why do I want to stay on cgroup v1?

According to the kubernetes annoucement, it is not ready for us to upgrade the JDK version.

```python
If you deploy Java applications with the JDK, prefer to use JDK 11.0.16 and later or JDK 15 and later, which [fully support cgroup v2](https://bugs.openjdk.org/browse/JDK-8230305).
```

**Comment by markusboehme** [comment]
There is no definitive date for removing cgroup v1 support in Bottlerocket yet. The latest -k8s variants defaulting to cgroup v1 are those targeting Kubernetes 1.25, which will be supported well into 2024, and we don't intend to change defaults for already released variants. Support for cgroup v1 may be removed in components Bottlerocket depends on before that date. An example of this is systemd which [aims to remove it in the first release in 2024](https://github.com/systemd/systemd/blob/c8ae0a81bfd5669c6da672cdf86119fb07feb575/NEWS#L25). We will have to deal with those changes within Bottlerocket as they appear, for systemd e.g. by using a [systemd-stable](https://github.com/systemd/systemd-stable) release.

For your situation, I am assuming that you are running on JDK 8, is that right? Only the JDK versions 8, 11, 17, 20 are currently within their upstream support window and of those only JDK 8 does not currently support cgroup v2. Perusing the OpenJDK issue tracker, it looks like there is an OpenJDK 8 release coming (8u372) which will have support for cgroup v2 backported ([main issue](https://bugs.openjdk.org/browse/JDK-8230305), [backport issue](https://bugs.openjdk.org/browse/JDK-8297880), [release notes](https://bugs.openjdk.org/browse/JDK-8305562)). Extrapolating from the past release schedule OpenJDK 8u372 is likely to be released this month.

(After OpenJDK 8u372 is out, we'll want to make sure the Kubernetes docs get updated.)

**Comment by hitsub2** [comment]
Thanks @markusboehme. So before remove cgroup v1 in Bottlerocket, it still has v1 and v2 in BR, right? We can choose to use v1 or v2 as follows? Variants for 1.26 is already default to v2, but we can still use v1 right?:
```python
[settings.boot]
reboot-to-reconcile = true

[settings.boot.init]
"systemd.unified_cgroup_hierarchy" = ["1"]

```

**Comment by markusboehme** [comment]
Yes, that's right, Bottlerocket supports both cgroup v1 and cgroup v2. With Bottlerocket 1.13.0, only the defaults for new variants changed. You can still choose to use cgroup v1 with Bottlerocket variants for Kubernetes 1.26, though support for it will likely disappear together with the last variant that defaulted to it (i.e. when the Kubernetes 1.25 variants reach end of life). By then, the upcoming OpenJDK 8 release with cgroup v2 support will have removed the update blocker for workloads requiring JDK 8.

Please note that in the snippet you need to set `"systemd.unified_cgroup_hierarchy" = ["0"]` (i.e. `0` instead of `1`) to use cgroup v1. This value is treated as a boolean rather than the cgroup version, with "unified cgroup hierarchy" being another common name for "cgroup v2".

**Comment by arnaldo2792** [comment]
Closing for now since the question originally asked was answered.

**Comment by markusboehme** [comment]
OpenJDK 8u372 with support for cgroup v2 has been released.

> (After OpenJDK 8u372 is out, we'll want to make sure the Kubernetes docs get updated.)

https://github.com/kubernetes/website/pull/40189
