### ISSUE TITLE
bootconfig.data

### ISSUE THREAD

**Issue by pedro-n-rocha** [bottlerocket-os/bottlerocket#3040]
Hi there, 

Congrats on the interesting project, I have been toying around with bottlerocket-os , and was able to do a build of the project, I had to tinker with buildsys because of containerd buildkit and nerdctl as I do not have the legacy docker installed, but it gave me more insights on the image build process so i finally generated the final img files.

Now, inspecting the boot process efi + grub + vmlinuz , I came across this line in the end of grub.cfg: initrd ($private)/bootconfig.data , traced the private var  back to EFI blob pointing  to a BOTTLEROCKET-PRIVATE label partition, all good, but  since /etc on ext4 is almost empty I was hoping to better understand the boot process, but bootconfig.data does not seem a ramfs as I was expecting in fact it seems a text file with contents 
kernel {}
init {}
y#BOOTCONFIG

so at this point I am a bit lost regarding init process of bottlerocket. I also run the image through Qemu , it loads the kernel but does not boot to anything, 

Can you clarify or point me to documentation regarding inirtd, I am curious how is customization handled on this boot fase. 

Thank you. 
Pedro

![image](https://user-images.githubusercontent.com/6649058/233424892-4071f210-a6bb-4e12-ab9d-c4d04ea4e7c6.png)

**Comment by zmrow** [comment]
Hi @pedro-n-rocha !  

Bottlerocket makes use of a Linux kernel feature called Boot Configuration.  The tl;dr of this feature is that it allows a user to pass additional arguments on the kernel command line at runtime.  These additional arguments are encoded inside an initrd and as you've found, are read in by the `initrd` parameter in `grub`.

Since Bottlerocket doesn't use an initrd for anything except Boot Configuration, the initrd is by default empty save for the encoded data you found.

Additional documentation of Bottlerocket's use of Boot Configuration is in the [metal documentation here](https://github.com/bottlerocket-os/bottlerocket/blob/a9e8697c4ac58744d2443c0905f341085446ed92/PROVISIONING-METAL.md#boot-configuration).  The [kernel documentation](https://www.kernel.org/doc/html/latest/admin-guide/bootconfig.html) on the feature is pretty great as well.

The `tools/` directory contains a great script called [`start-local-vm`](https://github.com/bottlerocket-os/bottlerocket/blob/develop/tools/start-local-vm) which should make the process of running Bottlerocket via qemu much easier.  For local use and just poking around, it makes sense to use a `-dev` variant like `aws-dev`.  This variant does not expect an orchestrator and includes docker.

Also - if you're ok with it I'd like to move this to a discussion unless there is a bug we should report.  Are you ok with that?

**Comment by pedro-n-rocha** [comment]
sure I am ok ofc.  

thanks for the clear explanation, I am  going  to check those links, always keen in learning new things :) 


Thanks
Pedro
