### ISSUE TITLE
iSCSI issues with CSI driver

### ISSUE THREAD

**Issue by naveenbansalntnx** [bottlerocket-os/bottlerocket#3276]
**What I'd like:** I am using a CSI driver which uses iSCSI connection to create and mount volume. But I am having trouble installing iSCSI on host. Is this feature not supported or there is a way that I am missing ?

**Any alternatives you've considered:**

**Comment by stmcginnis** [comment]
Hi @naveenbansalntnx. You are correct that this is not currently supported. There is an existing issue requesting that iSCSI support be added: https://github.com/bottlerocket-os/bottlerocket/issues/2570#issuecomment-1507662690

You will need to use a different storage protocol for now, unfortunately.

**Comment by naveenbansalntnx** [comment]
@stmcginnis okay , Thanks for confirming.

**Comment by d3bt3ch** [comment]
@stmcginnis Any possibility of supporting `iscsi` on `bottlerocket` anytime soon?

**Comment by stmcginnis** [comment]
Work still needs to be done to add the necessary components to support that. Things are being tracked in #2570, though I don't think anyone has been able to jump on that one yet. Contributions are welcome of course, but otherwise I think it might be some time before any of the maintainers can get to that.

If you could comment on that issue that you would like to see this capability, that could help in showing interest when trying to prioritize things.
