### ISSUE TITLE
How to modify a system flag on boot

### ISSUE THREAD

**Issue by DanOfir** [bottlerocket-os/bottlerocket#3447]
Hi,

I am trying to modify read ahead size on boot, The modify command is: "blockdev --setra 16 /dev/nvme1n1"

on a regular Linux 2 when this command runs inside "rc.local" file everything works as expected.

What is the best way to modify this on a bottlerocket OS?

**Comment by stmcginnis** [comment]
Hey @DanOfir - good question.

Running system commands like this with Bottlerocket is a little different. And unfortunately a little more complicated since in general we try to avoid modifying things with the host OS other than through exposed config settings.

In order to make a similar change on Bottlerocket, you will need to use a [bootstrap container](https://github.com/bottlerocket-os/bottlerocket/blob/develop/README.md#bootstrap-containers-settings). This is a special container with extra permissions that is able to make system modifications before the host has completed full initialization. It would be a container image you would create that would run whatever special initialization steps you would like to do as part of its entrypoint.

The underlying host OS filesystem is mounted inside this container under `/.bottlerocket/rootfs`. So for your specific case, I believe you would run something like:

```sh
blockdev --setra 16 /.bottlerocket/rootfs/dev/nvme1n1
```

It's an entirely different question and use case, but this discussion has some extra details beyond those in the README that help illustrate how a bootstrap container would be created and used: https://github.com/bottlerocket-os/bottlerocket/discussions/3338

I hope that helps! Please let me know if you have any questions or run in to any problems with this.

**Comment by DanOfir** [comment]
Amazing! Thank you very much @stmcginnis for this quick response, it was very helpful! and it works!

**Comment by stmcginnis** [comment]
> and it works!

Awesome! 🎉
