### ISSUE TITLE
.featureGates.RotateKubeletServerCertificate dropped from kubelet config in k8s 1.28

### ISSUE THREAD

**Issue by errm** [bottlerocket-os/bottlerocket#3506]
**Image I'm using:**

`bottlerocket-aws-k8s-1.28-x86_64-v1.15.0-c9af43ad`

**What I expected to happen:**

I am benchmarking against CIS guidelines using [kube-bench](https://github.com/aquasecurity/kube-bench)

Test 3.2.11 starts to fail when I upgrade to k8s 1.28.

This control is checking for the presence of `.featureGates.RotateKubeletServerCertificate` in the kubelet config.

**What actually happened:**

Images for kubernetes 1.27 and below included the following in `packages/kubernetes-1.x/kubelet-config`

```
 featureGates:
   RotateKubeletServerCertificate: true
```

This seems to have been removed from the kubernetes-1.28 package without any comment or information in the relevant commit https://github.com/bottlerocket-os/bottlerocket/commit/bf9e579c905736e1868a841a15efc0824f4096b6

I want to understand if this was an intentional change?  

There seems to be some test code here https://github.com/bottlerocket-os/bottlerocket/blob/develop/sources/bloodhound/README.md that should run this check... but I can't tell if it is run as part of the build process ...

**How to reproduce the problem:**

Run kube-bench against a bottlerocket - k8s 1.28 image.

**Comment by stmcginnis** [comment]
Hi @errm - sorry, that should maybe have been called out more clearly than just passing comments.

This feature gate is actually [enabled by default since Kubernetes 1.12](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/). So there wasn't really a reason to ever have it present in the config file with any of the versions Bottlerocket supports.

The reference you found in Bloodhound may actually be very interesting to you if you are trying to run the CIS Benchmarks. I'm sure you've seen a few other things that are just a little bit different in Bottlerocket that causes problems trying to use some of the tools designed for general purpose OSs. Bloodhound is an internal tool that was added and exposed through `apiclient` for [running the Bottlerocket or Kubernetes CIS benchmarks](https://github.com/bottlerocket-os/bottlerocket/tree/develop/sources/api/apiclient#report-mode). They provide either a nicely formatted human-readable format or a JSON formatted report that can be convenient for piping in to other programmatic reporting tools.

You can get a little more background context with the [Bottlerocket CIS report](https://github.com/bottlerocket-os/bottlerocket/pull/2881) and [Kubernetes CIS report](https://github.com/bottlerocket-os/bottlerocket/pull/3239) PRs.

Just let me know if you have any questions.

**Comment by errm** [comment]
> This feature gate is actually [enabled by default since Kubernetes 1.12](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/). So there wasn't really a reason to ever have it present in the config file with any of the versions Bottlerocket supports.

Yes thanks - that was my suspicion

I was a bit confused though because this config seems to have appeared in bottlerocket for k8s 1.23 - then went away again now for 1.28 - and that didn't seem like it lined up with this feature gate becoming a default.

I think the correct thing in my case is probably to make a PR to kube-bench so it can understand this default correctly, just like bloodhound does here https://github.com/bottlerocket-os/bottlerocket/blob/develop/sources/bloodhound/src/bin/kubernetes-checks/checks.rs#L596-L599
