### ISSUE TITLE
kubelet: pod-infra-container-image flag does not work with containerd

### ISSUE THREAD

**Issue by bcressey** [bottlerocket-os/bottlerocket#351]
> Warning: For remote container runtime, --pod-infra-container-image is ignored in kubelet, which should be set in that remote runtime instead

To address this, we need to:
- [ ] remove this flag from kubelet unit file
- [ ] drop `settings.kubernetes.pod_infra_container_image`
- [ ] add `settings.containerd.sandbox_image`
- [ ] convert `/etc/containerd/config.toml` and `host-containerd-config.toml` to templates
- [ ] modify `pluto` to support the renamed setting

**Comment by etungsten** [comment]
`containerd/cri` is not able to fetch the pause container image on its own (containerd/containerd#6637)

After a bit of discussion, we decided to reinstitute the `pod_infra_container_image` due to potential issues with `imagegc` garbage collecting the pause container (more context here https://github.com/kubernetes/kubernetes/issues/81756). 

Also decided to modify `host-ctr` to allow a `fetch-only` operation to pull images so we can fetch the pause container image before starting `kubelet`.
