### ISSUE TITLE
New setting under `settings.container-runtime` for configuring (`stargz`/`soci`) snapshotter for lazy image pulling

### ISSUE THREAD

**Issue by VariableExp0rt** [bottlerocket-os/bottlerocket#3716]
**What I'd like:**
This is a speculative request to be able to patch the `containerd` settings in this file https://github.com/bottlerocket-os/bottlerocket/blob/develop/packages/containerd/containerd-config-toml_k8s_containerd_sock with configuration related to [stargz-snapshotter](https://github.com/containerd/stargz-snapshotter/blob/main/docs/INSTALL.md#install-stargz-snapshotter-for-containerd-with-systemd) for eStargz and/or the [soci-snapshotter](https://github.com/awslabs/soci-snapshotter/blob/main/docs/getting-started.md).

I'd just like to know if this is something that could be supported, or is a terrible suggestion.

**Any alternatives you've considered:**
Not using stargz/SOCI.

**Comment by arnaldo2792** [comment]
Hello @VariableExp0rt, we already have an open issue to add support for SOCI (See https://github.com/bottlerocket-os/bottlerocket/issues/3017). I don't think folks have asked to support stargz, and seems that adding support for one of them seems sufficient.

Due to Bottlerocket's security features, it is a bit tricky to make SOCI work. We are still investigating how to add this support.

Since, as I said, there is an existing issue, could you please +1 on it since this is a duplicate?

**Comment by VariableExp0rt** [comment]
@arnaldo2792 sure, absolutely! Thank you for the quick response 💪🏻
