### ISSUE TITLE
Add additional ECS configuration values to `settings.ecs`

### ISSUE THREAD

**Issue by cbgbt** [bottlerocket-os/bottlerocket#3717]
**What I'd like:**
Add support for configuring the following values for ecs-agent:
* [ECS_BACKEND_HOST](https://github.com/aws/amazon-ecs-agent/blob/61c8a8c5b48e2efb7193fe61c4bb3cae816f5821/agent/config/config.go#L528)
* [ECS_AWSVPC_BLOCK_IMDS](https://github.com/aws/amazon-ecs-agent/blob/61c8a8c5b48e2efb7193fe61c4bb3cae816f5821/agent/config/config.go#L570)

**Any alternatives you've considered:**
n/a

**Comment by jtschelling** [comment]
tacking this on here.......i also need support for configuring [ECS_ENABLE_CONTAINER_METADATA](https://github.com/aws/amazon-ecs-agent/blob/61c8a8c5b48e2efb7193fe61c4bb3cae816f5821/agent/config/config.go#L572)

is there a way we can set these arbitrarily without having to make individual issues/pr's for every config available to the ecs-agent?

**Comment by DenzD** [comment]
@jtschelling I have reconfigured my services to use ecs_container_metadata_uri_v4.

**Comment by arnaldo2792** [comment]
While working on supporting `ECS_ENABLE_CONTAINER_METADATA`, I realized that due to how we configure the ECS agent, this feature won't work unless we patch the ECS agent.

When the ECS agent attempts to mount the metadata file on the task's container, it will use the directory `${ECS_HOST_DATA_DIR}/${ECS_DATADIR}`. In normal circumstances, the values for these environment variables will be `/var/lib/ecs` and `/data`, respectively, and the resulting path for the directory will be `/var/lib/ecs/data`. In Bottlerocket, we change `ECS_DATADIR` to be `/var/lib/ecs` without changing the default value of `ECS_HOST_DATA_DIR`. That results on the ECS agent creating the metadata file for the container at `/var/lib/ecs/data/metadata`, as expected, but the mounted directory will be `/var/lib/ecs/var/lib/ecs/data` due to the overridden `ECS_DATADIR`.

Setting `ECS_HOST_DATA_DIR` as an empty string isn't an option since that value is used by other features like Firelens.
