### ISSUE TITLE
Specify autoloaded kernel module options via settings.

### ISSUE THREAD

**Issue by james-masson** [bottlerocket-os/bottlerocket#3747]
**What I'd like:**

A setting to control an auto-loaded kernel module's options.
Extending from https://bottlerocket.dev/en/os/1.18.x/api/settings/kernel/#modules_autoload ...

eg.

```
[settings.kernel.modules.ip_vs_lc]
allowed = true
autoload = true
options = [ "my_option = enabled", "my_second_option = disabled" ] 
```

**Any alternatives you've considered:**

We currently toggle these module options after it's loaded, using a superpowered container.

**Comment by ecpullen** [comment]
Thanks for reaching out. We will look into supporting this in the future.

**Comment by foersleo** [comment]
While we look into addressing this, you should also be able to set the options via the kernel command line through user data. 

However, the trade off there would be, between an extra reboot of the host on first start vs. maintaining your container definitions for the superpowered containers setting those options.

If you use the kernel command line you will also have to set the `reboot-to-reconcile` option, which will delay the host being ready by the time it takes to reboot the host to actually use the new command line.

Going by your example from the original post your user data would look like this:

```
[settings.kernel.modules.ip_vs_lc]
allowed = true
autoload = true

[settings.boot]
reboot-to-reconcile = true

[settings.boot.kernel-parameters]
"ip_vs_lc.my_option" = [
  "enabled"
]
"ip_vs_lc.my_second_option" = [
  "disabled" 
]
```

**Comment by foersleo** [comment]
I took a closer look at this and I believe going the route of configuring this through the kernel command line and relying on `settings.boot.reboot-to-reconcile` as mentioned above is the right way to go.

A bit of background info that led me to that assessment:

Kernel modules can either be built into the kernel (they are part of the kernel binaries and do not need to be loaded explicitly) or built as loadable modules (they come as their own binary module that needs to be loaded in order to be used). Whether a module is built into the kernel or built as a loadable module is a distribution's implementation detail, and may change from one release to the next. Module authors can specify certain configuration options to tweak module behavior.

There is four main ways to set these module options:

1. Some module options are exposed through sysfs under `/sys/module/<module_name>/parameters/<option_name>`, where they may be changed during runtime. This method has its limitations as module authors can decide which options are exposed through this interface, and if the option can be read or written and by whom. 
2. As part of manual loading like `modprobe <module_name> <option_name>=<option_value>`. This sets the appropriate options to the desired setting when manually/interactively loading a module.
3. Setting `modprobe` defaults to be picked up by `udev` on boot from `.conf` files under `/etc/modprobe.d/`. Add options to these files in the format `options <module_name> <option_name>=<option_value>` to ensure adequate settings when loading modules on boot.
4. Through the kernel command line as `<module_name>.<option_name>=<option_value>`. This is the most versatile method as it is covering all modules, regardless of if they are built-in or built as loadable module. In fact this is the only way to set options for built-in modules.

Bottlerocket users have an extra layer of abstraction (user-data and how it is handled) between themselves and these interfaces. That extra layer is supposed to make things easier and they should not need to research if a module is built-in or not, if it was already loaded or not, and if that specific option can be set during runtime or only at load time. Documenting that for every module is probably more confusing than it would help, especially if we consider that that documentation could get outdated quickly by changing the kernels configuration to built-in a previously not built-in module.

The safest method is to set module options through the interface that already exists with `settings.boot.kernel-parameters` and requiring `settings.boot.reboot-to-reconcile` to cover all possible statuses a module could be in. The one downside to this is the extra reboot you incur when you reboot for the first time after you change module options. So if you create a Bottlerocket instance with user-data to model what I proposed in my previous post you will get 1 extra reboot on the first startup of that instance, when it constructs the kernel command line from the user-data and reboots to activate these settings.

I think there is not really any code work to be done here. However, I do see the need to properly document this way of how to set module options in Bottlerocket. I will see to suggest a documentation change PR by end of this week to get this fixed.

**Comment by foersleo** [comment]
The updated documentation has been released on the project website and now contains a hint to set module parameters through `settings.boot.kernel-parameters` (See https://bottlerocket.dev/en/os/1.19.x/api/settings/kernel/#modules_autoload).

Closing this issue. Feel free to open a new issue or reopen this one if you feel there is more to be done here.
