### ISSUE TITLE
Use a bottle rocket AMI in an AWS EC2 Image Pipeline

### ISSUE THREAD

**Issue by krayzie32** [bottlerocket-os/bottlerocket#3796]
**Platform I'm building on:**
AWS EC2 Image Pipeline

**What I expected to happen:**
The company that I work for is requesting that the bottle rocket AMI be used in our AWS EC2 image pipeline, where it would be subject to the STIG build action, along with others, to ensure that the image complies with our security guidelines.

I expected the AMI to pass the default build workflow (like the AWS eks-node AMI did).

**What actually happened:**
 I created a default pipeline with the bottle rocket AMI (`ami-04c60863bff6154c4`) and it doesn't get the past the first step, which is to be able to communicate with the SSM agent that is provided with the AMI.

**How to reproduce the problem:**
Via EC2 image builder, create an Image recipe with the custom AMI ID (from above), select the stage-build-linux-high build component, the reboot-test-linux test component, and leave the other sections as default options.

Create an infrastructure configuration that includes default options, but ensure that the subnet and security groups allow for SSM connectivity.

Create an image pipeline, that includes the above two items, and run the pipeline. The pipeline will not make it past the first step and the following error is observed: `An error occurred (InvalidInstanceId) when calling the SendCommand operation: Instances i-123456789 not in a valid state for account 12345678910 in workflow step LanuchBuildInstance`

Overall, is your AMI compatible with the EC2 Image Builder/Image pipeline mechanism? Thank you!

**Comment by ginglis13** [comment]
Hi @krayzie32, thanks for the issue. The short answer is no, Bottlerocket AMIs and EC2 Image builder / Image Pipeline are not compatible.

The longer answer is due to Bottlerocket's security features. Bottlerocket AMIs do not come equipped with an SSM agent running at the host level; rather, they run the SSM agent through the control container (https://github.com/bottlerocket-os/bottlerocket-control-container). Bottlerocket also ships with an immutable root filesystem, so even if the SSM agent were available at the host level, any changes attempted to the host's rootfs via SSM commands would fail. 

> ensure that the image complies with our security guidelines

I'd suggest you check out [SECURITY_FEATURES.md](https://github.com/bottlerocket-os/bottlerocket/blob/develop/SECURITY_FEATURES.md) and [SECURITY_GUIDANCE.md](https://github.com/bottlerocket-os/bottlerocket/blob/develop/SECURITY_GUIDANCE.md) to see if Bottlerocket's security posture meets the requirements for your company. 

If your company evaluates security based on CIS benchmarks, Bottlerocket comes equipped with tooling to run those benchmarks via the `apiclient`: check out the [docs here](https://github.com/bottlerocket-os/bottlerocket/tree/29cc92cc78974fd65c275972a4a65e8e1c1a34fe/sources/api/apiclient#report-mode) if that's relevant to you

**Comment by krayzie32** [comment]
@ginglis13 Thank you very much for the detailed reply.

**Comment by adubkov** [comment]
@krayzie32 what you ended up with? is the bottlerocket STIG-complient?

**Comment by krayzie32** [comment]
> [@krayzie32](https://github.com/krayzie32) what you ended up with? is the bottlerocket STIG-complient?

Users are now able to use approved scripts to create an AMI based off of bottlerocket. I can't find the AWS blog post on it... but it's out there.
