### ISSUE TITLE
SSM Node Management to install packages

### ISSUE THREAD

**Issue by FernandoMiguel** [bottlerocket-os/bottlerocket#3819]
**What I'd like:**
Our Security team wishes to install a security package to our EKS nodes running Bottlerocket using AWS SSM Node Management.

Given the immutability of Bottlerocket, what is the best way to install this package?

**Any alternatives you've considered:**
Moving off Bottletocket and use Amazon Linux instead :(

**Comment by webern** [comment]
Since Bottlerocket's security posture includes:

> The root filesystem is marked as read-only and cannot be directly modified by userspace processes.
(from https://github.com/bottlerocket-os/bottlerocket/blob/develop/SECURITY_FEATURES.md)

It is not possible to install software on the host.

Many of the vulnerabilities being scanned for by security software are not relevant on Bottlerocket due to its security features. Depending on the relationship with the security team, it may be possible to understand the purpose of the scanner and see if it is actually needed on Bottlerocket.

However, if the software must be used, then the options are:
- Run the software in a Kubernetes-orchestrated daemonset.
- If that is not possible, it may be possible to build a container with the software and run it as a host container on Bottlerocket.

If neither of those will do, and you must have the software on the host, then it becomes necessary to build your own custom, immutable variant of Bottlerocket which includes the software you need. We have a project underway to make this easier, but it will still be a while. Some users have built their own variants using a fork of Bottlerocket.

We would be happy to further discuss the details of what you need to run and what it's requirements are. That can be done here, or if you have a technical account manager, you can reach out to us through that channel.

**Comment by FernandoMiguel** [comment]
Hi @webern 
`daemonset` is the way we are trying to push the security team to implement this, but they are not familiar with containers or K8s, so it is challenging for them

Thanks for clarifying this for us.
