### ISSUE TITLE
Question: how to use "kubectl debug node" with bottlerocket?

### ISSUE THREAD

**Issue by max-rocket-internet** [bottlerocket-os/bottlerocket#4011]
`kubectl` added some great options under the `debug` command and even the main Kubernetes docs have a page about debugging nodes with it [here](https://kubernetes.io/docs/tasks/debug/debug-cluster/kubectl-node-debug/). You can see some technical details [here](https://github.com/kubernetes/enhancements/tree/master/keps/sig-cli/1441-kubectl-debug#node-troubleshooting-with-privileged-containers) about how it works.

```shell
kubectl debug node/ip-10-10-10-10.compute.internal -it --image=ubuntu
```

But obviously `chroot /host` does not work.

Is there some way to make this work? To access to `enter-admin-container` from `kubectl debug node`? It would be great because it would allow host debug without leaving `kubectl` 🙏

**Comment by arnaldo2792** [comment]
There is a way (and TIL, thanks for sharing `kubectl debug`!). You can do this:

```
kubectl debug node/<node> -it --image=<image>:<tag> --profile=sysadmin
```

And in the newly created pod:

```
chroot /host apiclient exec admin bash
```

And you should be at the admin container now (provided that you have the `admin` container enabled). But, keep in mind the high privilege you are giving to the pod, make sure you its gone after you are done debugging!

> But obviously chroot /host does not work.

It does! But by default it will try to execute a shell, which we don't have in Bottlerocket. So, you can still run commands like `chroot /host journalctl` or `chroot /host ctr -n k8s.io tasks ls` to debug some things, but you will be limited to what the host provides. That's why I posted how to enter the admin container from the debug pod, so that you can install tools if you need them.

**Comment by max-rocket-internet** [comment]
OK interesting @arnaldo2792! But where do you get this `profile`? I'm using version`v1.28.3` and it's not there:

```sh
~ kubectl debug node/ip-10-10-19-38.eu-west-1.compute.internal --profile=sysadmin -it --image=ubuntu
error: unknown profile: sysadmin
```

**Comment by arnaldo2792** [comment]
The profiles are version-dependent. I used `kubelet` v1.30.X, and it allowed me to use the `sysadmin` profile:

```
~  ❯ kubectl version
Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.9-eks-036c24b
```

**Comment by max-rocket-internet** [comment]
@arnaldo2792 can I open a PR to update the FAQ? If so, where? It would be quite useful to share this I think.

**Comment by arnaldo2792** [comment]
Of course! I think this will be the best place to document this:

https://github.com/bottlerocket-os/bottlerocket-project-website

Under [FAQ items]

[FAQ items]: https://github.com/bottlerocket-os/bottlerocket-project-website/tree/main/content/en/faqitems

**Comment by max-rocket-internet** [comment]
Alright, nice: https://github.com/bottlerocket-os/bottlerocket-project-website/pull/459
