### ISSUE TITLE
enable hardening features for service units

### ISSUE THREAD

**Issue by bcressey** [bottlerocket-os/bottlerocket#808]
**What I'd like:**
`systemd-analyze security` should turn green where possible.

Useful articles:
* [systemd service sandboxing and security hardening 101](https://www.ctrl.blog/entry/systemd-service-hardening.html)
* [Limit the impact of a security intrusion with systemd security directives](https://www.ctrl.blog/entry/systemd-opensmtpd-hardening.html)

**Any alternatives you've considered:**
N/A

**Comment by arnaldo2792** [comment]
We will be implementing this incrementally, and there will be bite-sized issues to sandbox the systemd services closely after this issue is closed so that we can include a few sandboxed systemd services per release.

The individual issues will refer to this issue to make it easier for users to track the progress of sandboxing the systemd services.
