### ISSUE TITLE
Migration: API integration

### ISSUE THREAD

**Issue by tjkirch** [bottlerocket-os/bottlerocket#89]
Assuming the API will expose system update status, we will want to expose migration status as part of it - at least as a potential failure reason.

**Comment by cbgbt** [comment]
With [migrations being planned to be performed by settings extensions](https://github.com/bottlerocket-os/bottlerocket/blob/a0f017341de02728671c8e46c094860eb3df0f4b/docs/design/settings/extensions/modular-settings-extensions.md#extension-versioning-and-migrations) and at `set` time rather than boot, I think we can close this.
