### ISSUE TITLE
Using Wants not Requires on configured.target 

### ISSUE THREAD

**Issue by tjkirch** [bottlerocket-os/bottlerocket#98]
(See #96)

The kubelet, docker, and containerd service files have dependencies on configured.target that are expressed with Wants instead of Requires.

This means that if configured.target fails at boot, kubelet and friends will start, even though we know we haven't generated the configuration files they need.

(This was done to avoid an even worse problem - if we used Requires, then kubelet and friends would stop or restart if the configuration utilities stopped or restarted; the configuration utilities should definitely not have an impact on the runtime of kubelet and friends once started.)

We couldn't find a way to express what we want in systemd, but we should continue research to show that it doesn't actually exist, and then consider our possible approaches:
* augment systemd
* wrap kubelet (and friends) to add domain knowledge
* your idea here?

**Comment by arnaldo2792** [comment]
I think this was resolved in #1423. With the new systemd boot sequence, kubelet, docker, and the ecs agent won't start if any of the required dependencies (early-boot-config, apiserver, containerd, etc) fails to start. We still use Wants instead of Requires to prevent unwanted reloads, when by some reason either the configured or preconfigured target are restarted. We added `RefuseManualStart` and `RefuseManualStop` to all the oneshot services. apiserver can still be restarted without restarting the entire services tree.
